# Generated by Django 4.2 on 2024-11-11 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('ID_Habilidade', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('Nombre_Habilidad', models.CharField(max_length=100, verbose_name='Nombre Habilidad')),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='DetalleHabilidades',
            fields=[
                ('ID_DetalleHabilidades', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('ID_Postulante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postulante.postulante', verbose_name='Postulante')),
                ('Id_Habilidades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='habilidades.habilidades', verbose_name='Habilidades')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Habilidades',
            },
        ),
    ]
