# Generated by Django 4.2 on 2024-11-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPlaza',
            fields=[
                ('ID_AreaPLAZA', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=16, unique=True, verbose_name='Código')),
                ('Descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Areas de Plazas',
            },
        ),
    ]
